# Circuit Configuration File
#	Manchester Mark I Reduced Machine

[global]
	pi_board_mode = "BOARD"		# BOARD/BCM

# User-controlled fields for the naming of constants later in the circuit configuration file.
[constants]
	LINE_LENGTH = 20
	WORD_LENGTH = 20
	PAGE_SIZE = 32
	PAGES_PER_TUBE = 2
	S_TUBES = 2

	SUB_CYCLES = 9

	DELAY = 0.001


	[constants.pin_names]
		# To FPGA
		TPR_CLK = 	3
		TPR_DATA = 	5
		S_CLK =		23
		S_DATA =	11
		PS =		13
		KSP = 		15
		SS =		19
		KLC =		21
		KSC = 		8
		WE =		22
		KCC = 		12
		CLK = 		24
		
		# From FPGA
		SL =		10
		#DISP_CLK =	12
		DISP_DATA =	16
		OSC =		26


[pin_inputs]
	[pin_inputs.PS]
		PIN = "pin_names.PS"

	[pin_inputs.KSP]
		PIN = "pin_names.KSP"

	[pin_inputs.KLC]
		PIN = "pin_names.KLC"

	[pin_inputs.KSC]
		PIN = "pin_names.KSC"

	[pin_inputs.WE]
		PIN = "pin_names.WE"

	[pin_inputs.SS]
		PIN = "pin_names.SS"

	[pin_inputs.KCC]
		PIN = "pin_names.KCC"

[pin_outputs]


# The Serial Inputs
#	NB: Regarding inputs with shared data pins:
#		Attempting to output over two serial ports which share the same data pin at the same
#		time results in UNDEFINED BEHAVIOUR.
[serial_inputs]
	[serial_inputs.TPR]
		BUS_WIDTH = "LINE_LENGTH"
		PIN_CLK = "pin_names.TPR_CLK"
		PIN_DATA = "pin_names.TPR_DATA"
		DELAY = "DELAY"

	[serial_inputs.S]
		BUS_WIDTH = "WORD_LENGTH"
		PIN_CLK = "pin_names.S_CLK"
		PIN_DATA = "pin_names.S_DATA"
		DELAY = "DELAY"


[serial_outputs]

# The Virtual Oscilloscopes
# 	NB: Multiple oscs can be run over the same clock and data pins.  The run time of the OSCs
#	scales linearly with the max of all BUS_WIDTHS of all OSCS which share the same data pin
[virtual_oscs]
	[virtual_oscs.main]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 50
		# BUS_LABELS used for plotting purposes only
		BUS_LABELS = ["w_CLK", "w_HS", "w_HA", "w_PP_WF", "w_PPU_retrig", "w_S1", "w_CL_YPLATE", "w_INSTR_GATE", "w_ACTION_AUTO", "W_ACTION_MAN", "w_ACTION", "w_PARA_ACTION", "~w_PPU_retrig",
		
		"b_MS_DATA_OUT[0]", "b_MS_DATA_OUT[1]", "b_MS_DATA_OUT[2]", "b_MS_DATA_OUT[3]", "b_MS_DATA_OUT[4]", 
		"b_MS_DATA_IN[0]", "b_MS_DATA_IN[1]", "b_MS_DATA_IN[2]", "b_MS_DATA_IN[3]", "b_MS_DATA_IN[4]", 
		"b_FST_DATA_OUT[0]", "b_FST_DATA_OUT[1]", "b_FST_DATA_OUT[2]", "b_FST_DATA_OUT[3]", "b_FST_DATA_OUT[4]", "b_FST_DATA_OUT[5]",
		"w_A_ZERO", 
		"b_A_DATA_IN[0]", "b_A_DATA_IN[1]", "b_A_DATA_IN[2]", "b_A_DATA_IN[3]", "b_A_DATA_IN[4]", 
		"b_A_DATA_OUT[0]", "b_A_DATA_OUT[1]", "b_A_DATA_OUT[2]", "b_A_DATA_OUT[3]", "b_A_DATA_OUT[4]", 
		"word_addr[0]", "word_addr[1]", "word_addr[2]", "word_addr[3]", "word_addr[4]", 
		"tube_addr[0]", "tube_addr[1]", "tube_addr[2]", "tube_addr[3]", "tube_addr[4]", 

		]
		DELAY = "DELAY"

	[virtual_oscs.controller]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 10
		BUS_LABELS = ["TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST"]
		DELAY = "DELAY"

	[virtual_oscs.timing]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 10
		BUS_LABELS = ["TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST"]
		DELAY = "DELAY"

	[virtual_oscs.instruction_decoding]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 10
		BUS_LABELS = ["TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST"]
		DELAY = "DELAY"

	[virtual_oscs.data_flow]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 10
		BUS_LABELS = ["TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST"]
		DELAY = "DELAY"

	[virtual_oscs.main_store]
		PIN_CLK = "pin_names.CLK"
		PIN_DATA = "pin_names.OSC"
		BUS_WIDTH = 10
		BUS_LABELS = ["TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST", "TEST"]
		DELAY = "DELAY"

